### ISSUE TITLE
consider improving the tuning_profile code flow

### ISSUE THREAD

**Issue by scorpevans** [pg-spot-ops/pg-spot-operator#22]
The current approach does some kind of eval($profile.py).
Proper interface classes could be setup, so developers could inherit and implement some functions to fit their specs.

related https://github.com/pg-spot-ops/pg-spot-operator/issues/72

**Comment by kmoppel** [comment]
Now a bit better - good enough for now I think after https://github.com/pg-spot-ops/pg-spot-operator/pull/116

**Comment by kmoppel** [comment]
Can inject custom settings anyways via manifests
